# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_remove_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 22, 17, 58, 56, 126365, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 22, 17, 59, 19, 673277, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
