# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 21:19
from __future__ import unicode_literals

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20160719_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_image_path),
        ),
    ]
