# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 15:28
from __future__ import unicode_literals

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_image_path),
        ),
    ]
