# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20160721_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pic',
        ),
    ]
