# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-22 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 22, 18, 34, 23, 668466, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 22, 18, 34, 31, 171504, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
