# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 16:14
from __future__ import unicode_literals

import collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_item_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.image_path, verbose_name='item'),
        ),
    ]
